import { User } from './User';

export const USERS: User[] = [
  {
    id: 0,
    user_name: "CiaraTheCool",
    fname: "Ciara",
    sname: "Galvin",
    dob: new Date(),
    location: "Co. Kerry",
    image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQyMDA0MzcxNjM3NDEyOTI3/harry-styles_gettyimages-476076862jpg.jpg",
    gender: "Female",
    sexuality: "Cool",
    bio: "I love Harry!!!",
  },
  {
    id: 1,
    user_name: "Conor McGov",
    fname: "Conor",
    sname: "McGovern",
    dob: new Date(),
    location: "Co. Mayo",
    image: "https://i.kym-cdn.com/photos/images/original/001/661/466/b4b",
    gender: "Male",
    sexuality: "Done",
    bio: "I love Harry MORE!!!",
  },
  {
    id: 0,
    user_name: "CiaraTheCool",
    fname: "Ciara",
    sname: "Galvin",
    dob: new Date(),
    location: "Co. Kerry",
    image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQyMDA0MzcxNjM3NDEyOTI3/harry-styles_gettyimages-476076862jpg.jpg",
    gender: "Female",
    sexuality: "Cool",
    bio: "I love Harry!!!",
  },
  {
    id: 1,
    user_name: "Conor McGov",
    fname: "Conor",
    sname: "McGovern",
    dob: new Date(),
    location: "Co. Mayo",
    image: "https://i.kym-cdn.com/photos/images/original/001/661/466/b4b",
    gender: "Male",
    sexuality: "Done",
    bio: "I love Harry MORE!!!",
  },
  {
    id: 0,
    user_name: "CiaraTheCool",
    fname: "Ciara",
    sname: "Galvin",
    dob: new Date(),
    location: "Co. Kerry",
    image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQyMDA0MzcxNjM3NDEyOTI3/harry-styles_gettyimages-476076862jpg.jpg",
    gender: "Female",
    sexuality: "Cool",
    bio: "I love Harry!!!",
  },
  {
    id: 1,
    user_name: "Conor McGov",
    fname: "Conor",
    sname: "McGovern",
    dob: new Date(),
    location: "Co. Mayo",
    image: "https://i.kym-cdn.com/photos/images/original/001/661/466/b4b",
    gender: "Male",
    sexuality: "Done",
    bio: "I love Harry MORE!!!",
  },
  {
    id: 0,
    user_name: "CiaraTheCool",
    fname: "Ciara",
    sname: "Galvin",
    dob: new Date(),
    location: "Co. Kerry",
    image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQyMDA0MzcxNjM3NDEyOTI3/harry-styles_gettyimages-476076862jpg.jpg",
    gender: "Female",
    sexuality: "Cool",
    bio: "I love Harry!!!",
  },
  {
    id: 1,
    user_name: "Conor McGov",
    fname: "Conor",
    sname: "McGovern",
    dob: new Date(),
    location: "Co. Mayo",
    image: "https://i.kym-cdn.com/photos/images/original/001/661/466/b4b",
    gender: "Male",
    sexuality: "Done",
    bio: "I love Harry MORE!!!",
  },
  {
    id: 0,
    user_name: "CiaraTheCool",
    fname: "Ciara",
    sname: "Galvin",
    dob: new Date(),
    location: "Co. Kerry",
    image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQyMDA0MzcxNjM3NDEyOTI3/harry-styles_gettyimages-476076862jpg.jpg",
    gender: "Female",
    sexuality: "Cool",
    bio: "I love Harry!!!",
  },
  {
    id: 1,
    user_name: "Conor McGov",
    fname: "Conor",
    sname: "McGovern",
    dob: new Date(),
    location: "Co. Mayo",
    image: "https://i.kym-cdn.com/photos/images/original/001/661/466/b4b",
    gender: "Male",
    sexuality: "Done",
    bio: "I love Harry MORE!!!",
  },
  {
    id: 0,
    user_name: "CiaraTheCool",
    fname: "Ciara",
    sname: "Galvin",
    dob: new Date(),
    location: "Co. Kerry",
    image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQyMDA0MzcxNjM3NDEyOTI3/harry-styles_gettyimages-476076862jpg.jpg",
    gender: "Female",
    sexuality: "Cool",
    bio: "I love Harry!!!",
  },
  {
    id: 1,
    user_name: "Conor McGov",
    fname: "Conor",
    sname: "McGovern",
    dob: new Date(),
    location: "Co. Mayo",
    image: "https://i.kym-cdn.com/photos/images/original/001/661/466/b4b",
    gender: "Male",
    sexuality: "Done",
    bio: "I love Harry MORE!!!",
  },
  {
    id: 0,
    user_name: "CiaraTheCool",
    fname: "Ciara",
    sname: "Galvin",
    dob: new Date(),
    location: "Co. Kerry",
    image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQyMDA0MzcxNjM3NDEyOTI3/harry-styles_gettyimages-476076862jpg.jpg",
    gender: "Female",
    sexuality: "Cool",
    bio: "I love Harry!!!",
  },
  {
    id: 1,
    user_name: "Conor McGov",
    fname: "Conor",
    sname: "McGovern",
    dob: new Date(),
    location: "Co. Mayo",
    image: "https://i.kym-cdn.com/photos/images/original/001/661/466/b4b",
    gender: "Male",
    sexuality: "Done",
    bio: "I love Harry MORE!!!",
  },
  {
    id: 0,
    user_name: "CiaraTheCool",
    fname: "Ciara",
    sname: "Galvin",
    dob: new Date(),
    location: "Co. Kerry",
    image: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQyMDA0MzcxNjM3NDEyOTI3/harry-styles_gettyimages-476076862jpg.jpg",
    gender: "Female",
    sexuality: "Cool",
    bio: "I love Harry!!!",
  },
  {
    id: 1,
    user_name: "Conor McGov",
    fname: "Conor",
    sname: "McGovern",
    dob: new Date(),
    location: "Co. Mayo",
    image: "https://i.kym-cdn.com/photos/images/original/001/661/466/b4b",
    gender: "Male",
    sexuality: "Done",
    bio: "I love Harry MORE!!!",
  }
]
